DROP TABLE IF EXISTS `VA_VIRTUAL_ACCT_TYPE`;
CREATE TABLE `VA_VIRTUAL_ACCT_TYPE` (
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '账户类型',
  `VIR_ACCT_DESC` VARCHAR(100) NOT NULL COMMENT '类型描述',
  `VIR_ACCT_SORT` VARCHAR(16) NOT NULL COMMENT '账户归属类别',
  `IS_IN` VARCHAR(4) NOT NULL COMMENT '是否允许转入',
  `IS_OUT` VARCHAR(4) NOT NULL COMMENT '是否允许转出',
  `IS_TOTAL_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否有总额限制',
  `TOTAL_LIMIT` DECIMAL(20,8) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否留备付金',
  `BALANCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` DECIMAL(20,8) DEFAULT NULL COMMENT '备付金限额数值',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新柜员',
  `UPDATE_DATE` VARCHAR(14) DEFAULT NULL COMMENT '更新日期',
  `BZ` VARCHAR(100) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`VIR_ACCT_TYPE`)
)COMMENT='虚拟账户类型表';

DROP TABLE IF EXISTS `VA_CUST_INFO`;
CREATE TABLE `VA_CUST_INFO` (
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `USER_ID` VARCHAR(32) NOT NULL COMMENT '会员用户编号',
  `CUST_NAME` VARCHAR(100) NOT NULL COMMENT '会员姓名',
  `STATUS` VARCHAR(4) NOT NULL COMMENT '会员状态 N:正常；C：注销；W:未激活',
  `GLOBAL_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '证件类型',
  `GLOBAL_ID` VARCHAR(32) DEFAULT NULL COMMENT '证件号码',
  `TEL_NO` VARCHAR(32) DEFAULT NULL COMMENT '电话号码',
  `EMAIL` VARCHAR(32) DEFAULT NULL COMMENT '邮箱',
  `ADRESS` VARCHAR(200) DEFAULT NULL COMMENT '居住地址',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '交易平台编号',
  `CREATE_DATE` DATETIME DEFAULT NULL COMMENT '建立日期',
  `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '建立操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '注销日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '注销操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `SOURCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '来源',
  `CUST_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '会员类别',
  `CUST_LEVEL` VARCHAR(4) DEFAULT NULL COMMENT '会员等级',
  `ALLOW_USER` VARCHAR(32) DEFAULT NULL COMMENT '审批操作员',
  `ALLOW_DATE` DATETIME DEFAULT NULL COMMENT '审批时间',
  `ALLOW_STATUS` VARCHAR(4) DEFAULT NULL COMMENT '审批状态',
  PRIMARY KEY (`CUST_ID`)
) COMMENT='会员信息表';

DROP TABLE IF EXISTS `VA_PLAT_INFO`;
CREATE TABLE `VA_PLAT_INFO` (
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `PAY_MERCH_ID` VARCHAR(32) NOT NULL COMMENT '支付商户编号',
  `PLAT_NAME` VARCHAR(100) NOT NULL COMMENT '平台名称',
  `LEGAL_PERSON` VARCHAR(32) NOT NULL COMMENT '法人姓名',
  `STATUS` VARCHAR(4) NOT NULL COMMENT '商户状态  N：正常  C：注销 ',
  `PAYMENT_TYPE` VARCHAR(4) NOT NULL COMMENT '结算类型 0-手动申请；1-日终自动结算',
  `GLOBAL_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '法人证件类型',
  `GLOBAL_ID` VARCHAR(32) DEFAULT NULL COMMENT '法人证件号码',
  `TEL_NO` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `EMAIL` VARCHAR(32) DEFAULT NULL COMMENT '企业邮箱',
  `ADRESS` VARCHAR(200) DEFAULT NULL COMMENT '企业地址',
  `URL` VARCHAR(200) DEFAULT NULL COMMENT '企业网址',
  `CREATE_DATE` DATETIME DEFAULT NULL COMMENT '建立日期',
  `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '建立操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '注销日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '注销操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  `SOURCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '来源',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `PLAT_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '平台类别',
  `PLAT_LEVEL` VARCHAR(4) DEFAULT NULL COMMENT '平台等级',
  `ALLOW_USER` VARCHAR(32) DEFAULT NULL COMMENT '审批操作员',
  `ALLOW_DATE` DATETIME DEFAULT NULL COMMENT '审批时间',
  `ALLOW_STATUS` VARCHAR(4) DEFAULT NULL COMMENT '审批状态',
  PRIMARY KEY (`PLAT_ID`)
)COMMENT='平台信息表' ;

DROP TABLE IF EXISTS `VA_MERCH_VIRTUAL_ACCT_BAL`;
CREATE TABLE `VA_MERCH_VIRTUAL_ACCT_BAL` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '商户虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` DECIMAL(20,8) DEFAULT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`)
)COMMENT='商户虚拟账户余额信息表' ;

DROP TABLE IF EXISTS `VA_CUST_VIRTUAL_ACCT_BAL`;
CREATE TABLE `VA_CUST_VIRTUAL_ACCT_BAL` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '会员虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '虚拟账户类型',
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` DECIMAL(20,8) DEFAULT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`)
) COMMENT='会员虚拟账户余额信息表';

DROP TABLE IF EXISTS `VA_CUST_VIRTUAL_ACCT`;
CREATE TABLE `VA_CUST_VIRTUAL_ACCT` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '会员虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '虚拟账户类型',
  `VIR_ACCT_SORT` VARCHAR(16) NOT NULL COMMENT '账户归属类别',
  `VIR_ACCT_NAME` VARCHAR(100) NOT NULL COMMENT '虚拟账户名称',
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `CUST_NAME` VARCHAR(100) DEFAULT NULL COMMENT '会员名称',
  `USER_ID` VARCHAR(32) NOT NULL COMMENT '会员用户编号',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '交易平台编号',
  `PLAT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '平台名称',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态',
  `REL_BANK_ACCT` VARCHAR(32) DEFAULT NULL COMMENT '关联银行账户',
  `IS_IN` VARCHAR(4) DEFAULT NULL COMMENT '是否允许转入',
  `IS_OUT` VARCHAR(4) DEFAULT NULL COMMENT '是否允许转出',
  `IS_TOTAL_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否有总额限制',
  `TOTAL_LIMIT` DECIMAL(17,2) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否留备付金',
  `BALANCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` DECIMAL(17,2) DEFAULT NULL COMMENT '备付金限额数值',
  `OPEN_DATE` DATETIME DEFAULT NULL COMMENT '开户日期',
  `OPEN_USER` VARCHAR(32) DEFAULT NULL COMMENT '开户操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '销户日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '销户操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '状态更新日期',
  `SOURCE_USER` VARCHAR(32) DEFAULT NULL COMMENT '状态更新操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  PRIMARY KEY (`VIR_ACCT_ID`)
)COMMENT='会员虚拟账户信息表' ;

DROP TABLE IF EXISTS `VA_MERCH_INFO`;
CREATE TABLE `VA_MERCH_INFO` (
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `STATUS` VARCHAR(4) NOT NULL COMMENT '商户状态  N：正常  C：注销 ',
  `PAY_MERCH_ID` VARCHAR(32) NOT NULL COMMENT '支付商户编号',
  `MERCH_NAME` VARCHAR(100) NOT NULL COMMENT '商户名称',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '交易平台编号',
  `LEGAL_PERSON` VARCHAR(32) NOT NULL COMMENT '法人姓名',
  `PAYMENT_TYPE` VARCHAR(4) NOT NULL COMMENT '结算类型 0-商户手动申请；1-日终自动结算',
  `GLOBAL_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '法人证件类型',
  `GLOBAL_ID` VARCHAR(32) DEFAULT NULL COMMENT '法人证件号码',
  `TEL_NO` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `EMAIL` VARCHAR(32) DEFAULT NULL COMMENT '企业邮箱',
  `ADRESS` VARCHAR(200) DEFAULT NULL COMMENT '企业地址',
  `URL` VARCHAR(200) DEFAULT NULL COMMENT '企业网址',
  `CREATE_DATE` DATETIME DEFAULT NULL COMMENT '建立日期',
  `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '建立操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '注销日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '注销操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  `SOURCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '来源',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `MERCH_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '商户类别',
  `MERCH_LEVEL` VARCHAR(4) DEFAULT NULL COMMENT '商户等级',
  `ALLOW_USER` VARCHAR(32) DEFAULT NULL COMMENT '审批操作员',
  `ALLOW_DATE` DATETIME DEFAULT NULL COMMENT '审批时间',
  `ALLOW_STATUS` VARCHAR(4) DEFAULT NULL COMMENT '审批状态',
  PRIMARY KEY (`MERCH_ID`)
)COMMENT='商户信息表' ;

DROP TABLE IF EXISTS `VA_MERCH_VIRTUAL_ACCT`;
CREATE TABLE `VA_MERCH_VIRTUAL_ACCT` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '商户虚拟账户编号',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '账户类型',
  `VIR_ACCT_SORT` VARCHAR(16) NOT NULL COMMENT '账户归属类别 1：会员 2：商户 3：交易平台',
  `VIR_ACCT_NAME` VARCHAR(100) NOT NULL COMMENT '虚拟账户名称',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '交易平台编号',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态 N：正常 F：冻结C：注销',
  `REL_BANK_ACCT` VARCHAR(32) NOT NULL COMMENT '关联银行账户',
  `IS_IN` VARCHAR(4) NOT NULL COMMENT '是否允许转入Y：是 N:否',
  `IS_OUT` VARCHAR(4) NOT NULL COMMENT '是否允许转出Y：是 N:否',
  `IS_TOTAL_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否有总额限制Y：是 N:否',
  `TOTAL_LIMIT` DECIMAL(17,2) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否留备付金Y：是 N:否',
  `BALANCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` DECIMAL(17,2) DEFAULT NULL COMMENT '备付金限额数值',
  `OPEN_DATE` DATETIME DEFAULT NULL COMMENT '开户日期',
  `OPEN_USER` VARCHAR(32) DEFAULT NULL COMMENT '开户操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '销户日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '销户操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '状态更新日期',
  `SOURCE_USER` VARCHAR(32) DEFAULT NULL COMMENT '状态更新操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  `MERCH_NAME` VARCHAR(100) DEFAULT NULL COMMENT '商户名称',
  `PLAT_NAME` VARCHAR(32) DEFAULT NULL COMMENT '平台名称',
  PRIMARY KEY (`VIR_ACCT_ID`)
) COMMENT='商户虚拟账户信息表';

DROP TABLE IF EXISTS `VA_PLAT_ACCT_INFO`;
CREATE TABLE `VA_PLAT_ACCT_INFO` (
  `ACCT_ID` VARCHAR(32) NOT NULL COMMENT '账户编号',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `ACCT_TYPE` VARCHAR(32) NOT NULL COMMENT '账户类型 0：结算账户1：交易平台存管专户2：银行内部账户',
  `ACCT_NO` VARCHAR(32) NOT NULL COMMENT '账户',
  `ACCT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '账户名称',
  `IS_THIS_BANK` VARCHAR(4) DEFAULT NULL COMMENT '是否本行账户',
  `ACCT_BR_NO` VARCHAR(32) DEFAULT NULL COMMENT '开户行号',
  `ACCT_BR_NAME` VARCHAR(100) DEFAULT NULL COMMENT '开户行名称',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态N：正常F：冻结C：注销',
  `ACCT_CATEGORY` VARCHAR(100) DEFAULT NULL  COMMENT '账户类别',
  PRIMARY KEY (`ACCT_ID`)
) COMMENT='平台银行账户信息表';

DROP TABLE IF EXISTS `VA_MERCH_VIRTUAL_ACCT_BAL_DAY`;
CREATE TABLE `VA_MERCH_VIRTUAL_ACCT_BAL_DAY` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '商户虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `SYS_DATE` DATETIME NOT NULL COMMENT '系统日期',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` VARCHAR(32) NOT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`,`MERCH_ID`,`SYS_DATE`)
)COMMENT='商户日终余额信息表' ;

DROP TABLE IF EXISTS `VA_CUST_VIRTUAL_ACCT_BAL_DAY`;
CREATE TABLE `VA_CUST_VIRTUAL_ACCT_BAL_DAY` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '个人虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '个人编号',
  `SYS_DATE` DATETIME NOT NULL COMMENT '系统日期',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` VARCHAR(32) NOT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`,`CUST_ID`,`SYS_DATE`)
)COMMENT='个人日终余额信息表' ;

DROP TABLE IF EXISTS `VA_PLAT_VIRTUAL_ACCT_BAL_DAY`;
CREATE TABLE `VA_PLAT_VIRTUAL_ACCT_BAL_DAY` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '平台虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `SYS_DATE` DATETIME NOT NULL COMMENT '系统日期',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` VARCHAR(32) NOT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`,`PLAT_ID`,`SYS_DATE`)
)COMMENT='平台日终余额信息表' ;


DROP TABLE IF EXISTS `VA_MERCH_ACCT_INFO`;
CREATE TABLE `VA_MERCH_ACCT_INFO` (
  `ACCT_ID` VARCHAR(32) NOT NULL COMMENT '账户编号',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `ACCT_TYPE` VARCHAR(32) NOT NULL COMMENT '账户类型 0：结算账户1：交易平台存管专户2：银行内部账户',
  `ACCT_NO` VARCHAR(32) NOT NULL COMMENT '账户',
  `ACCT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '账户名称',
  `IS_THIS_BANK` VARCHAR(4) DEFAULT NULL COMMENT '是否本行账户',
  `ACCT_BR_NO` VARCHAR(32) DEFAULT NULL COMMENT '开户行号',
  `ACCT_BR_NAME` VARCHAR(100) DEFAULT NULL COMMENT '开户行名称',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态N：正常F：冻结C：注销',
  `ACCT_CATEGORY` VARCHAR(100) DEFAULT NULL  COMMENT '账户类别',
  PRIMARY KEY (`ACCT_ID`)
)COMMENT='商户银行账户信息表' ;

DROP TABLE IF EXISTS `VA_CUST_ACCT_INFO`;
CREATE TABLE `VA_CUST_ACCT_INFO` (
  `ACCT_ID` VARCHAR(32) NOT NULL COMMENT '账户编号',
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `ACCT_TYPE` VARCHAR(32) NOT NULL COMMENT '账户类型 0：结算账户1：交易平台存管专户2：银行内部账户',
  `ACCT_NO` VARCHAR(32) NOT NULL COMMENT '账户',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态N：正常F：冻结C：注销',
  `ACCT_CATEGORY` VARCHAR(100) DEFAULT NULL  COMMENT '账户类别',
  `ACCT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '账户名称',
  `IS_THIS_BANK` VARCHAR(4) DEFAULT NULL COMMENT '是否本行账户',
  `ACCT_BR_NO` VARCHAR(32) DEFAULT NULL COMMENT '开户行号',
  `ACCT_BR_NAME` VARCHAR(100) DEFAULT NULL COMMENT '开户行名称',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '更新日期',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新操作员',
  PRIMARY KEY (`ACCT_ID`)
)COMMENT='会员银行账户信息表' ;

DROP TABLE IF EXISTS VA_USER;
CREATE TABLE VA_USER(
	USER_ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30),
	AGE INT DEFAULT 0,
	PRIMARY KEY(USER_ID)
)COMMENT='用户信息';

DROP TABLE IF EXISTS `VA_PLAT_VIRTUAL_ACCT`;
CREATE TABLE `VA_PLAT_VIRTUAL_ACCT` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '平台虚拟账户编号',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '账户类型',
  `VIR_ACCT_SORT` VARCHAR(16) NOT NULL COMMENT '账户归属类别 1：会员 2：平台 3：交易平台',
  `VIR_ACCT_NAME` VARCHAR(100) NOT NULL COMMENT '虚拟账户名称',
  `CURRENCY` VARCHAR(4) NOT NULL COMMENT '币种',
  `ACCT_STATUS` VARCHAR(4) NOT NULL COMMENT '账户状态 N：正常 F：冻结C：注销',
  `REL_BANK_ACCT` VARCHAR(32) NOT NULL COMMENT '关联银行账户',
  `IS_IN` VARCHAR(4) NOT NULL COMMENT '是否允许转入Y：是 N:否',
  `IS_OUT` VARCHAR(4) NOT NULL COMMENT '是否允许转出Y：是 N:否',
  `IS_TOTAL_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否有总额限制Y：是 N:否',
  `TOTAL_LIMIT` DECIMAL(17,2) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否留备付金Y：是 N:否',
  `BALANCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` DECIMAL(17,2) DEFAULT NULL COMMENT '备付金限额数值',
  `OPEN_DATE` DATETIME DEFAULT NULL COMMENT '开户日期',
  `OPEN_USER` VARCHAR(32) DEFAULT NULL COMMENT '开户操作员',
  `CANCEL_DATE` DATETIME DEFAULT NULL COMMENT '销户日期',
  `CANCEL_USER` VARCHAR(32) DEFAULT NULL COMMENT '销户操作员',
  `UPDATE_DATE` DATETIME DEFAULT NULL COMMENT '状态更新日期',
  `SOURCE_USER` VARCHAR(32) DEFAULT NULL COMMENT '状态更新操作员',
  `EFFECT_DATE` DATETIME DEFAULT NULL COMMENT '有效期',
  `PLAT_NAME` VARCHAR(32) DEFAULT NULL COMMENT '平台名称',
  PRIMARY KEY (`VIR_ACCT_ID`)
) ;

DROP TABLE IF EXISTS `VA_PLAT_VIRTUAL_ACCT_BAL`;
CREATE TABLE `VA_PLAT_VIRTUAL_ACCT_BAL` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '平台虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` DECIMAL(20,8) DEFAULT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`)
) COMMENT '平台虚拟账户信息表';

DROP TABLE IF EXISTS `VA_PLAT_VIRTUAL_ACCT_BAL`;
CREATE TABLE `VA_PLAT_VIRTUAL_ACCT_BAL` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '平台虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` DECIMAL(20,8) DEFAULT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`)
) ;

##_____________________________________________________________________________________


DROP TABLE IF EXISTS VA_SEQUENCE;
CREATE TABLE VA_SEQUENCE(
SEQ_NAME VARCHAR(30),
CURR_VAL INT DEFAULT 0,
_INCREMENT INT DEFAULT 1,
_DESC VARCHAR(50),
PRIMARY KEY(SEQ_NAME)
);

DROP FUNCTION IF EXISTS GETCURRVAL;
CREATE FUNCTION GETCURRVAL(P_SEQ_NAME VARCHAR(38))RETURNS INT
BEGIN
	DECLARE VAL INT;
	SELECT CURR_VAL INTO VAL FROM VA_SEQUENCE WHERE SEQ_NAME=P_SEQ_NAME;
	RETURN VAL;
END;

DROP FUNCTION IF EXISTS GETNEXTVAL;
CREATE FUNCTION GETNEXTVAL(P_SEQ_NAME VARCHAR(38))RETURNS INT
BEGIN
	UPDATE VA_SEQUENCE SET CURR_VAL=CURR_VAL+_INCREMENT WHERE SEQ_NAME=P_SEQ_NAME;
	RETURN GETCURRVAL(P_SEQ_NAME);
END;