DROP TABLE IF EXISTS VA_CUST_RECHARGE_DETAIL;
CREATE TABLE `VA_CUST_RECHARGE_DETAIL` (
    `CUST_RECHARGE_SEQ` VARCHAR(32) NOT NULL COMMENT '会员充值流水号',
    `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务流水号',
    `ORDER_NO_OLD` VARCHAR(32) COMMENT '原业务流水号',
    `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
    `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
    `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '会员虚拟账户编号',
    `TRAN_TYPE` VARCHAR(4) NOT NULL COMMENT '交易类型',
    `TRAN_AMT` DECIMAL(20,8) NOT NULL COMMENT '交易金额',
    `TRAN_STATUS` DECIMAL(20,8) NOT NULL COMMENT '交易状态',
    `TRAN_DATE` DATE NOT NULL COMMENT '交易日期',
    PRIMARY KEY (`CUST_RECHARGE_SEQ`)
    ) COMMENT='会员充值记录流水表';