DROP TABLE IF EXISTS `VA_merch_virtual_acct`;
CREATE TABLE `VA_merch_virtual_acct` (
  `VIR_ACCT_ID` varchar(32) NOT NULL COMMENT '商户虚拟账户编号',
  `MERCH_ID` varchar(32) NOT NULL COMMENT '商户编号',
  `VIR_ACCT_TYPE` varchar(16) NOT NULL COMMENT '账户类型',
  `VIR_ACCT_SORT` varchar(16) NOT NULL COMMENT '账户归属类别 1：会员 2：商户 3：交易平台',
  `VIR_ACCT_NAME` varchar(100) NOT NULL COMMENT '虚拟账户名称',
  `PLAT_ID` varchar(32) NOT NULL COMMENT '交易平台编号',
  `CURRENCY` varchar(4) NOT NULL COMMENT '币种',
  `ACCT_STATUS` varchar(4) NOT NULL COMMENT '账户状态 N：正常 F：冻结C：注销',
  `REL_BANK_ACCT` varchar(32) NOT NULL COMMENT '关联银行账户',
  `IS_IN` varchar(4) NOT NULL COMMENT '是否允许转入Y：是 N:否',
  `IS_OUT` varchar(4) NOT NULL COMMENT '是否允许转出Y：是 N:否',
  `IS_TOTAL_LIMIT` varchar(4) DEFAULT NULL COMMENT '是否有总额限制Y：是 N:否',
  `TOTAL_LIMIT` decimal(17,2) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` varchar(4) DEFAULT NULL COMMENT '是否留备付金Y：是 N:否',
  `BALANCE_TYPE` varchar(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` decimal(17,2) DEFAULT NULL COMMENT '备付金限额数值',
  `OPEN_DATE` datetime DEFAULT NULL COMMENT '开户日期',
  `OPEN_USER` varchar(32) DEFAULT NULL COMMENT '开户操作员',
  `CANCEL_DATE` datetime DEFAULT NULL COMMENT '销户日期',
  `CANCEL_USER` varchar(32) DEFAULT NULL COMMENT '销户操作员',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '状态更新日期',
  `SOURCE_USER` varchar(32) DEFAULT NULL COMMENT '状态更新操作员',
  `EFFECT_DATE` datetime DEFAULT NULL COMMENT '有效期',
  `MERCH_NAME` varchar(100) DEFAULT NULL COMMENT '商户名称',
  `PLAT_NAME` varchar(32) DEFAULT NULL COMMENT '平台名称',
  PRIMARY KEY (`VIR_ACCT_ID`)
) COMMENT='商户虚拟账户信息表';