DROP TABLE IF EXISTS VA_VIR_ACCT_SEQ;
CREATE TABLE VA_VIR_ACCT_SEQ(
	ORDER_ACCT_SEQ_NO VARCHAR(32) COMMENT '虚拟账务流水号',
	ORDER_NO  VARCHAR(32) NOT NULL COMMENT '订单号',
	ORDER_NO_OLD  VARCHAR(32) NOT NULL COMMENT '原订单号',
	CM_SEQ_NO VARCHAR(32) NOT NULL COMMENT '内部系统流水号',
	PLAT_ID VARCHAR(32) NOT NULL COMMENT '所属平台编号',
	BUYER_ID  VARCHAR(32) NOT NULL COMMENT '买方编号',
	BUYER_VIRID  VARCHAR(32) NOT NULL COMMENT '买方虚拟账户编号',
	BUYER_SORT varchar(4)  NOT NULL COMMENT '买方类别',
	SELLER_ID VARCHAR(32) NOT NULL COMMENT '卖方编号',
	SELLER_VIRID  VARCHAR(32) NOT NULL COMMENT '卖方虚拟账户编号',
	SELLER_SORT varchar(4)  NOT NULL COMMENT '卖方类别',
	PAY_TYPE VARCHAR(4) NOT NULL COMMENT '支付方式',
	TRAN_AMT DECIMAL(10,2) COMMENT '交易金额=使用的可用金额+使用的充值金额',
	USABLE_BAL DECIMAL(10,2) COMMENT '使用的可用金额',
	RECHARGE_BAL DECIMAL(10,2) COMMENT '使用的充值金额',
	TRAN_TYPE VARCHAR(4) NOT NULL COMMENT '交易类型',
	TRAN_STATUS  VARCHAR(4) NOT NULL COMMENT '交易状态',
	TRAN_DATE DATE  NOT NULL COMMENT '交易日期',
	TRAN_TIME DATE COMMENT '交易时间',
	PRIMARY KEY(ORDER_ACCT_SEQ_NO)
)COMMENT '虚拟账务流水表';
