DROP TABLE IF EXISTS  `CM_ACCT_TRAN_SEQ`;
CREATE TABLE CM_ACCT_TRAN_SEQ` (
  `TRAN_SEQ_NO`           VARCHAR(32)       NOT NULL COMMENT '流水号',
   `PUB_SEQ_NO` VARCHAR(32) NOT NULL COMMENT '公共流水号',
  `TRAN_DATE`             DATE COMMENT '交易日期',
  `TRAN_TIME`             VARCHAR(10) COMMENT '交易时间',
  `CURRENY`               VARCHAR(4) COMMENT '币种',
  `TRAN_AMT`              DECIMAL(17,2) COMMENT '交易金额',
  `TRAN_TYPE`             VARCHAR(16) COMMENT '交易类型',
 `BUSINESS_CODE`         VARCHAR(16) COMMENT '业务编码',
  `BUSINESS_NAME`         VARCHAR(100) COMMENT '业务编码名称',
  `ORDER_NO`              VARCHAR(32) COMMENT '业务流水号',
  `ORDER_NO_OLD`             VARCHAR(32) COMMENT '原业务流水号',
  `REF_NO`        VARCHAR(32) COMMENT '金融参考号',
  `MERCH_ID`         VARCHAR(32) COMMENT '商户编号',
  `MERCH_NAME`       VARCHAR(100) COMMENT '商户名称',
  `CUST_ID` VARCHAR(32) COMMENT '会员编号',
  `CUST_NAME`       VARCHAR(100) COMMENT '会员名称',
  `PAYER_NAME`            VARCHAR(100) COMMENT '付款方名称',
  `PAYER_VIR_ACCT_NO`     VARCHAR(32) COMMENT '付款人虚拟账户',
  `PAYEE_NAME`            VARCHAR(100) COMMENT '收款方名称',
  `PAYEE_VIR_ACCT_NO`     VARCHAR(32) COMMENT '收款方虚拟账户',
  `PLAT_ID`              VARCHAR(32) COMMENT '平台编号',
  `PLAT_NAME`          VARCHAR(100) COMMENT '平台名称',
  `PAYER_ACCT_NO`         VARCHAR(32) COMMENT '付款方账户',
  `PAYER_ACCT_NAME`       VARCHAR(100) COMMENT '付款方账户名称',
  `PAYER_ACCT_SORT`       VARCHAR(4) COMMENT '付款方账户类别：0会员；1商户；2交易平台',
  `PAYER_IS_THIS_BANK`    VARCHAR(4) COMMENT '付款方账户是否我行',
  `PAYER_ACCT_BANK_NO`    VARCHAR(32) COMMENT '付款方账户行号',
  `PAYER_ACCT_BANK_NAME`  VARCHAR(100) COMMENT '付款方账户行名称',
  `PAYEE_ACCT_NO`         VARCHAR(32) COMMENT '收款方账户账户',
  `PAYEE_ACCT_NAME`       VARCHAR(100) COMMENT '收款方账户名称',
  `PAYEE_ACCT_SORT`       VARCHAR(4) COMMENT '收款方账户类别：0会员；1商户；2交易平台',
  `PAYEE_IS_THIS_BANK`    VARCHAR(4) COMMENT '收款方账户是否我行',
  `PAYEE_ACCT_BANK_NO`   VARCHAR(32) COMMENT '收款方账户行号',
  `PAYEE_ACCT_BANK_NAME`  VARCHAR(100) COMMENT '收款方账户行名称',
  `TRAN_STATUS`           VARCHAR(4) COMMENT '交易状态:00-未发起,01-成功,02-失败,03-已冲正',
  `RET_CODE`              VARCHAR(16) COMMENT '响应码',
  `RET_MSG`               VARCHAR(200) COMMENT '响应信息',
  `HOST_SEQ_NO`          VARCHAR(32) COMMENT '关联系统流水号',
  `HOST_TRAN_STATUS`      VARCHAR(2) COMMENT '关联系统交易状态',
  `IS_CHECK`              VARCHAR(4) COMMENT '是否参与对账',
  `IS_RECOVER`            VARCHAR(4) COMMENT '是否冲正',
  `REVERSED`              VARCHAR(4) COMMENT '是否已被冲正',
  `OPER_TIME`             VARCHAR(20) COMMENT '操作时间',
  `USER_ID`               VARCHAR(32) COMMENT '柜员ID',
  `CONTRAST`              VARCHAR(4) COMMENT '对账状态:0-未对账,1-平账,2-差错,3-状态不一致,4-单边',
  `REFUND_STATUS`         VARCHAR(4) COMMENT '退款状态',
  PRIMARY KEY (`TRAN_SEQ_NO`)
)COMMENT '账务流水表';