DROP TABLE IF EXISTS `VA_CUST_RECHARGE_SEQ`;
CREATE TABLE `VA_CUST_RECHARGE_SEQ` (
    `CUST_RECHARGE_SEQ` VARCHAR(32) NOT NULL COMMENT '会员充值流水号',
    `PUB_SEQ_NO` VARCHAR(32) NOT NULL COMMENT '公共流水号',
    `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务流水号',
    `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
    `PAYEE_ID` VARCHAR(32) NOT NULL COMMENT '收款方编号',
    `PAYEE_VIRID` VARCHAR(32) NOT NULL COMMENT '收款方虚拟账户编号',
    `PAYER_ACCT_NO` VARCHAR(32) NOT NULL COMMENT '付款方银行账号',
    `TRAN_TYPE` VARCHAR(4) NOT NULL COMMENT '交易类型',
    `TRAN_AMT` DECIMAL(20,8) NOT NULL COMMENT '交易金额',
    `TRAN_DATE` DATE NOT NULL COMMENT '交易日期',
    PRIMARY KEY (`CUST_RECHARGE_SEQ`)
    ) COMMENT='会员充值记录流水表';