DROP TABLE IF EXISTS `VA_CUST_VIRTUAL_ACCT_BAL`;
CREATE TABLE `VA_CUST_VIRTUAL_ACCT_BAL` (
  `CUST_VIRID` VARCHAR(32) NOT NULL COMMENT '会员虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '虚拟账户类型',
  `CUST_ID` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` DECIMAL(20,8) DEFAULT NULL COMMENT '充值金额',
  PRIMARY KEY (`CUST_VIRID`)
) COMMENT='会员虚拟账户余额信息表';