DROP TABLE IF EXISTS `VA_MERCH_VIRTUAL_ACCT_BAL_DAY`;
CREATE TABLE `VA_MERCH_VIRTUAL_ACCT_BAL_DAY` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '商户虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
  `SYS_DATE` DATETIME NOT NULL COMMENT '系统日期',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  `RECHARGE_BAL` VARCHAR(32) NOT NULL COMMENT '充值金额',
  PRIMARY KEY (`VIR_ACCT_ID`,`MERCH_ID`,`SYS_DATE`)
)COMMENT='商户日终余额信息表' ;