DROP TABLE IF EXISTS `VA_MERCH_RECHARGE_SEQ`;
CREATE TABLE `VA_MERCH_RECHARGE_SEQ` (
    `MERCH_RECHARGE_SEQ` VARCHAR(32) NOT NULL COMMENT '商户充值流水号',
    `PUB_SEQ_NO` VARCHAR(32) NOT NULL COMMENT '公共流水号',
    `ORDER_NO` VARCHAR(32) NOT NULL COMMENT '业务流水号',
    `ORDER_NO_OLD` VARCHAR(32) COMMENT '原业务流水号',
    `PLAT_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
    `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '商户编号',
    `MERCH_VIRID` VARCHAR(32) NOT NULL COMMENT '商户虚拟账户编号',
    `PAYER_ACCT_NO` VARCHAR(32) NOT NULL COMMENT '付款账号',
    `TRAN_TYPE` VARCHAR(4) NOT NULL COMMENT '交易类型',
    `TRAN_AMT` DECIMAL(20,8) NOT NULL COMMENT '交易金额',
    `TRAN_STATUS` DECIMAL(20,8) NOT NULL COMMENT '交易状态',
    `TRAN_DATE` DATE NOT NULL COMMENT '交易日期',
    PRIMARY KEY (`MERCH_RECHARGE_SEQ`)
    ) COMMENT='商户充值记录流表';水