DROP TABLE IF EXISTS `VA_PLAT_VIRTUAL_ACCT_BAL_DAY`;
CREATE TABLE `VA_PLAT_VIRTUAL_ACCT_BAL_DAY` (
  `VIR_ACCT_ID` VARCHAR(32) NOT NULL COMMENT '平台虚拟账户编号',
  `VIR_ACCT_TYPE` VARCHAR(4) NOT NULL COMMENT '虚拟账户类型',
  `MERCH_ID` VARCHAR(32) NOT NULL COMMENT '平台编号',
  `SYS_DATE` DATETIME NOT NULL COMMENT '系统日期',
  `ACTURAL_BAL` DECIMAL(20,8) NOT NULL COMMENT '当前余额',
  `USABLE_BAL` DECIMAL(20,8) NOT NULL COMMENT '可用余额',
  `FREEZE_BAL` DECIMAL(20,8) NOT NULL COMMENT '冻结金额',
  PROCESS_TYPE VARCHAR(32) NOT NULL COMMENT '处理类型',
  PRIMARY KEY (`VIR_ACCT_ID`,`MERCH_ID`,`SYS_DATE`,`PROCESS_TYPE`)
) ;