DROP TABLE IF EXISTS VA_SEQUENCE_P;
  CREATE TABLE VA_SEQUENCE_P(
    SEQ_NAME VARCHAR(20) COMMENT '名称',
    _LENGTH INT(2)  COMMENT '设定长度',
    _PREFIX VARCHAR(8) comment '序列前缀',
    _DESC VARCHAR (50) COMMENT '描述',
    PRIMARY KEY (SEQ_NAME)
  );