DROP TABLE IF EXISTS `VA_VIRTUAL_ACCT_TYPE`;
CREATE TABLE `VA_VIRTUAL_ACCT_TYPE` (
  `VIR_ACCT_TYPE` VARCHAR(16) NOT NULL COMMENT '账户类型',
  `VIR_ACCT_DESC` VARCHAR(100) NOT NULL COMMENT '类型描述',
  `VIR_ACCT_SORT` VARCHAR(16) NOT NULL COMMENT '账户归属类别',
  `IS_IN` VARCHAR(4) NOT NULL COMMENT '是否允许转入',
  `IS_OUT` VARCHAR(4) NOT NULL COMMENT '是否允许转出',
  `IS_TOTAL_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否有总额限制',
  `TOTAL_LIMIT` DECIMAL(20,8) DEFAULT NULL COMMENT '总额限制',
  `IS_BALANCE_LIMIT` VARCHAR(4) DEFAULT NULL COMMENT '是否留备付金',
  `BALANCE_TYPE` VARCHAR(4) DEFAULT NULL COMMENT '备付金限额方式',
  `BALANCE_VALUE` DECIMAL(20,8) DEFAULT NULL COMMENT '备付金限额数值',
  `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新柜员',
  `UPDATE_DATE` VARCHAR(14) DEFAULT NULL COMMENT '更新日期',
  `BZ` VARCHAR(100) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`VIR_ACCT_TYPE`)
);